### PR TITLE
Modernized

### PR DESCRIPTION
**Pull request by jqnatividad**
Hi @jblondin, I'm hoping to use your library for [qsv](https://github.com/jqnatividad/qsv), thus this PR.

* modernized the code a bit with clippy
* addressed security advisory raised in #1 
* bumped dependencies

### CODE REVIEW

**Review by jblondin — APPROVED** [review]
LGTM!

**Comment by jqnatividad** [comment]
Awesome @jblondin ! Let me do a few more tweaks...

**Comment by jqnatividad** [comment]
Here you go! Hope it gets merged soon!

**Comment by jblondin** [comment]
Merged, bumped to version 0.2, published. Thank you so much!

**Comment by pinkforest** [comment]
Hi @jblondin this was fixed in 0.2 right ? I got an advisory https://github.com/rustsec/advisory-db/pull/1512 that claims it was fixed in 0.3 ? Just checking. Thanks

**Comment by J3rry-1729** [comment]
Yes I think the fix is 0.2

**Pull request merged**
